Repository amatzen/SE02-SE-G02-SPRO, pull requests merged in 2021-05, with the labels that each got.

#151 Renaming epg table
  src/main/java/dk/sdu/swe/domain/models/EPGProgramme.java
Labels: Domain

#157 Alt muligt ;)
  src/main/java/dk/sdu/swe/data/converters/JSONConverter.java
  src/main/java/dk/sdu/swe/data/converters/ListToJSONConverter.java
  src/main/java/dk/sdu/swe/data/converters/MapToJSONConverter.java
  src/main/java/dk/sdu/swe/data/converters/ProgrammeJSONConverter.java
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
  src/main/java/dk/sdu/swe/domain/models/Programme.java
  src/main/java/dk/sdu/swe/domain/models/Review.java
Labels: Domain

#159 So minimal change, that I had to create a commit
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
Labels: Domain

#162 + programme query fix
  src/main/java/dk/sdu/swe/data/dao/AbstractDAO.java
  src/main/java/dk/sdu/swe/data/dao/CategoryDAOImpl.java
  src/main/java/dk/sdu/swe/data/dao/ChannelDAOImpl.java
  src/main/java/dk/sdu/swe/data/dao/PersonDAOImpl.java
  src/main/java/dk/sdu/swe/data/dao/ProgrammeDAOImpl.java
  src/main/java/dk/sdu/swe/data/dao/UserDAOImpl.java
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
  src/main/java/dk/sdu/swe/domain/models/Programme.java
Labels: Domain

#164 Search by category title
  src/main/java/dk/sdu/swe/data/dao/ProgrammeDAOImpl.java
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
Labels: Domain

#166 🗡️
  src/main/java/dk/sdu/swe/Application.java
  src/main/java/dk/sdu/swe/data/DB.java
  src/main/java/dk/sdu/swe/data/SeederUtility.java
  src/main/java/dk/sdu/swe/data/dao/ProgrammeDAOImpl.java
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
  src/main/java/dk/sdu/swe/domain/controllers/UserController.java
Labels: Domain

#172 Credit role listview
  src/main/java/dk/sdu/swe/data/dao/CreditRoleDAOImpl.java
  src/main/java/dk/sdu/swe/data/dao/ProgrammeDAOImpl.java
  src/main/java/dk/sdu/swe/domain/controllers/CompanyController.java
  src/main/java/dk/sdu/swe/domain/controllers/CreditRoleController.java
  src/main/java/dk/sdu/swe/domain/controllers/UserController.java
  src/main/java/dk/sdu/swe/views/AdminViewController.java
  src/main/java/dk/sdu/swe/views/AppViewController.java
  src/main/java/dk/sdu/swe/views/CreditGroupController.java
  src/main/java/dk/sdu/swe/views/CreditGroupViewController.java
  src/main/java/dk/sdu/swe/views/DataExportController.java
  src/main/java/dk/sdu/swe/views/PersonsViewController.java
  src/main/java/dk/sdu/swe/views/ReviewViewController.java
  src/main/java/dk/sdu/swe/views/Router.java
  src/main/java/dk/sdu/swe/views/UserControlController.java
  src/main/java/dk/sdu/swe/views/UserControlViewController.java
  src/main/java/dk/sdu/swe/views/modals/companies/UserAdministrationModal.java
  src/main/java/dk/sdu/swe/views/modals/programmes/ProgrammeModal.java
  src/main/java/dk/sdu/swe/views/partials/CreditGroupListItem.java
  src/main/java/dk/sdu/swe/views/partials/ReviewItem.java
  src/main/java/dk/sdu/swe/views/partials/UserListItem.java
  src/main/resources/dk/sdu/swe/views/AppView.fxml
  src/main/resources/dk/sdu/swe/views/admin/AdminView.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/CreditGroupListItem.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/CreditGroupView.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/DataExportView.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/ReviewListItem.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/UserControlView.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/creditgroup.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/exportBar.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/usercontrol.fxml
  src/main/resources/dk/sdu/swe/views/credits/bulk-edit-credit.fxml
  src/main/resources/dk/sdu/swe/views/programmes/EditProgramme.fxml
  src/main/resources/dk/sdu/swe/views/programmes/ProgrammeModal.fxml
  src/main/resources/dk/sdu/swe/views/programmes/ProgrammesView.fxml
  src/main/resources/dk/sdu/swe/views/programmes/UserAdministrationModal.fxml
Labels: Presentation

#173 Data export
  src/main/java/dk/sdu/swe/domain/controllers/CreditController.java
  src/main/java/dk/sdu/swe/domain/models/CsvExport.java
  src/main/java/dk/sdu/swe/domain/models/JsonExport.java
  src/main/java/dk/sdu/swe/views/DataExportController.java
  src/main/resources/dk/sdu/swe/views/admin/components/DataExportView.fxml
Labels: Presentation

#174 Update list item state after editing.
  src/main/java/dk/sdu/swe/domain/controllers/CreditController.java
  src/main/java/dk/sdu/swe/views/AdminViewController.java
  src/main/java/dk/sdu/swe/views/DataExportViewController.java
  src/main/java/dk/sdu/swe/views/modals/credits/CreditModal.java
  src/main/java/dk/sdu/swe/views/modals/programmes/ProgrammeModal.java
  src/main/java/dk/sdu/swe/views/partials/CompanyListItem.java
  src/main/java/dk/sdu/swe/views/partials/CreditListItem.java
  src/main/java/dk/sdu/swe/views/partials/PersonListItem.java
  src/main/java/dk/sdu/swe/views/partials/ProgrammeListItem.java
  src/main/java/dk/sdu/swe/views/partials/UserListItem.java
  src/main/resources/dk/sdu/swe/views/admin/components/UserListItem.fxml
Labels: Presentation

#175 🧙‍♂️
  src/main/java/dk/sdu/swe/data/DB.java
  src/main/java/dk/sdu/swe/data/SeederUtility.java
  src/main/java/dk/sdu/swe/data/dao/ReviewDAOImpl.java
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
  src/main/java/dk/sdu/swe/domain/controllers/CompanyController.java
  src/main/java/dk/sdu/swe/domain/controllers/PersonController.java
  src/main/java/dk/sdu/swe/domain/models/Credit.java
  src/main/java/dk/sdu/swe/domain/models/Programme.java
  src/main/java/dk/sdu/swe/domain/models/Review.java
  src/main/java/dk/sdu/swe/domain/models/ReviewState.java
  src/main/java/dk/sdu/swe/domain/models/SystemAdministrator.java
  src/main/java/dk/sdu/swe/views/CompanyViewController.java
  src/main/java/dk/sdu/swe/views/PersonsViewController.java
  src/main/java/dk/sdu/swe/views/ProgrammesViewController.java
  src/main/java/dk/sdu/swe/views/modals/companies/CompanyModal.java
  src/main/java/dk/sdu/swe/views/modals/programmes/ProgrammeModal.java
  src/main/java/dk/sdu/swe/views/partials/CompanyListItem.java
  src/main/java/dk/sdu/swe/views/partials/ProgrammeListItem.java
  src/main/resources/dk/sdu/swe/ui/images/review_btn/rs_awaiting_active.png
  src/main/resources/dk/sdu/swe/ui/images/review_btn/rs_awaiting_default.png
  src/main/resources/dk/sdu/swe/ui/images/review_btn/rs_complete_active.png
  src/main/resources/dk/sdu/swe/ui/images/review_btn/rs_complete_default.png
  src/main/resources/dk/sdu/swe/ui/images/review_btn/rs_draft_active.png
  src/main/resources/dk/sdu/swe/ui/images/review_btn/rs_draft_default.png
  src/main/resources/dk/sdu/swe/views/programmes/ProgrammeListItem.fxml
Labels: Data, Domain, Presentation

#176 Most Important Pull Request!!!!!
  src/main/java/dk/sdu/swe/data/SeederUtility.java
  src/main/java/dk/sdu/swe/data/seeders/v4_AddGamerIArbejdstoej.java
  src/main/java/dk/sdu/swe/views/partials/ProgrammeListItem.java
  src/main/resources/dk/sdu/swe/views/companies/components/CompanyListItem.fxml
  src/main/resources/dk/sdu/swe/views/images/review_btn/rs_awaiting_active.png
  src/main/resources/dk/sdu/swe/views/images/review_btn/rs_awaiting_default.png
  src/main/resources/dk/sdu/swe/views/images/review_btn/rs_complete_active.png
  src/main/resources/dk/sdu/swe/views/images/review_btn/rs_complete_default.png
  src/main/resources/dk/sdu/swe/views/images/review_btn/rs_draft_active.png
  src/main/resources/dk/sdu/swe/views/images/review_btn/rs_draft_default.png
Labels: Data, Domain, Presentation

#177 🦠
  src/main/java/dk/sdu/swe/data/SeederUtility.java
  src/main/java/dk/sdu/swe/data/dao/AbstractDAO.java
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
  src/main/java/dk/sdu/swe/data/seeders/v5_AddPeopleAndCredits.java
  src/main/resources/dk/sdu/swe/views/credits/components/CreditListItem.fxml
  src/main/resources/dk/sdu/swe/views/persons/components/PersonListItem.fxml
  src/main/resources/dk/sdu/swe/views/programmes/ProgrammeListItem.fxml
Labels: Presentation

#178 Indicator bug fixes
  src/main/java/dk/sdu/swe/views/AdminViewController.java
  src/main/java/dk/sdu/swe/views/partials/Navbar.java
  src/main/resources/dk/sdu/swe/views/Navbar.css
  src/main/resources/dk/sdu/swe/views/admin/AdminView.fxml
Labels: Data, Presentation

#179 🌈
  build.gradle
  src/main/java/dk/sdu/swe/data/dao/CompanyDAOImpl.java
  src/main/java/dk/sdu/swe/domain/controllers/CreditRoleController.java
  src/main/java/dk/sdu/swe/domain/models/Credit.java
  src/main/java/dk/sdu/swe/domain/models/CreditRole.java
  src/main/java/dk/sdu/swe/domain/models/CsvExport.java
  src/main/java/dk/sdu/swe/domain/models/JsonExport.java
  src/main/java/dk/sdu/swe/views/CreditGroupViewController.java
  src/main/java/dk/sdu/swe/views/DataExportViewController.java
  src/main/java/dk/sdu/swe/views/UserControlViewController.java
  src/main/java/dk/sdu/swe/views/modals/credits/CreditRoleModal.java
  src/main/java/dk/sdu/swe/views/partials/CreditGroupListItem.java
  src/main/java/dk/sdu/swe/views/partials/UserControlListItem.java
  src/main/resources/dk/sdu/swe/views/admin/components/DataExportView.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/UserControlListItem.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/UserControlView.fxml
  src/main/resources/dk/sdu/swe/views/credits/CreditRoleModal.fxml
Labels: Presentation

#181 Some different changes
  src/main/java/dk/sdu/swe/data/seeders/v5_AddPeopleAndCredits.java
  src/main/java/dk/sdu/swe/domain/controllers/ProgrammeController.java
  src/main/java/dk/sdu/swe/domain/controllers/ReviewController.java
  src/main/java/dk/sdu/swe/domain/models/SystemAdministrator.java
  src/main/java/dk/sdu/swe/views/AdminViewController.java
  src/main/java/dk/sdu/swe/views/CreditGroupViewController.java
  src/main/java/dk/sdu/swe/views/ReviewViewController.java
  src/main/java/dk/sdu/swe/views/modals/credits/CreditGroupModal.java
  src/main/java/dk/sdu/swe/views/modals/programmes/ProgrammeModal.java
  src/main/java/dk/sdu/swe/views/partials/CreditGroupListItem.java
  src/main/java/dk/sdu/swe/views/partials/ReviewListItem.java
  src/main/resources/dk/sdu/swe/views/admin/components/CreditGroupModal.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/ReviewListItem.fxml
Labels: Presentation

#182 🛡👁👄👁🗡
  src/main/java/dk/sdu/swe/data/dao/ReviewDAOImpl.java
  src/main/java/dk/sdu/swe/data/seeders/v3_CreateProgrammesForThisWeek.java
  src/main/java/dk/sdu/swe/domain/controllers/ReviewController.java
  src/main/java/dk/sdu/swe/domain/models/User.java
  src/main/java/dk/sdu/swe/domain/persistence/IReviewDAO.java
  src/main/java/dk/sdu/swe/views/ProgrammesViewController.java
  src/main/java/dk/sdu/swe/views/ReviewViewController.java
  src/main/java/dk/sdu/swe/views/modals/programmes/ProgrammeModal.java
  src/main/java/dk/sdu/swe/views/partials/ReviewListItem.java
  src/main/resources/dk/sdu/swe/views/admin/AdminView.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/CreditGroupModal.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/CreditGroupView.fxml
  src/main/resources/dk/sdu/swe/views/admin/components/ReviewView.fxml
  src/main/resources/dk/sdu/swe/views/credits/CreditModal.fxml
  src/main/resources/dk/sdu/swe/views/programmes/ProgrammeListItem.fxml
Labels: Presentation

#183 Created contracts for controllers
  src/main/java/dk/sdu/swe/domain/controllers/ChannelController.java
  src/main/java/dk/sdu/swe/domain/controllers/CompanyController.java
  src/main/java/dk/sdu/swe/domain/controllers/CreditController.java
  src/main/java/dk/sdu/swe/domain/controllers/CreditRoleController.java
  src/main/java/dk/sdu/swe/domain/controllers/PersonController.java
  src/main/java/dk/sdu/swe/domain/controllers/ProgrammeController.java
  src/main/java/dk/sdu/swe/domain/controllers/ReviewController.java
  src/main/java/dk/sdu/swe/domain/controllers/UserController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IAuthController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IChannelController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/ICompanyController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/ICreditController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/ICreditRoleController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IPersonController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IProgrammeController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IReviewController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IUserController.java
Labels: Domain

#186 Fixed admin page indicator
  src/main/java/dk/sdu/swe/presentation/controllers/partials/Navbar.java
Labels: Domain

#189 Set title & added extension filter
  src/main/java/dk/sdu/swe/presentation/controllers/DataExportViewController.java
Labels: Domain

#192 👁🐝M
  src/main/java/dk/sdu/swe/domain/controllers/ReviewController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IReviewController.java
  src/main/java/dk/sdu/swe/domain/persistence/IReviewDAO.java
  src/main/java/dk/sdu/swe/presentation/controllers/partials/ProgrammeListItem.java
Labels: Domain

#193 Added initial filename + date format
  src/main/java/dk/sdu/swe/presentation/controllers/DataExportViewController.java
Labels: Domain

#201 jasan pr
  src/main/java/dk/sdu/swe/domain/controllers/contracts/ICreditController.java
Labels: Domain

#215 Added Exception
  src/main/java/dk/sdu/swe/domain/models/Person.java
  src/main/java/dk/sdu/swe/domain/models/User.java
  src/main/java/dk/sdu/swe/presentation/controllers/modals/persons/PersonModal.java
Labels: Domain

#217 Add missing channels
  src/main/java/dk/sdu/swe/persistence/dao/CompanyDAOImpl.java
  src/main/java/dk/sdu/swe/persistence/dao/PersonDAOImpl.java
  src/main/java/dk/sdu/swe/persistence/dao/ProgrammeDAOImpl.java
  src/main/java/dk/sdu/swe/persistence/seeders/v2_CreateChannels.java
Labels: Domain

#225 + Filter by programme ownership when searching
  src/main/java/dk/sdu/swe/domain/controllers/ProgrammeController.java
  src/main/java/dk/sdu/swe/persistence/dao/PersonDAOImpl.java
  src/main/java/dk/sdu/swe/persistence/dao/ProgrammeDAOImpl.java
Labels: Domain

#226 Path change
  src/main/java/dk/sdu/swe/ConsumerSystemAPI.java
Labels: Domain

#227 Fixed editing programmes
  src/main/java/dk/sdu/swe/domain/models/Programme.java
  src/main/java/dk/sdu/swe/presentation/Router.java
  src/main/java/dk/sdu/swe/presentation/controllers/AppViewController.java
  src/main/java/dk/sdu/swe/presentation/controllers/AuthViewController.java
  src/main/java/dk/sdu/swe/presentation/controllers/partials/Navbar.java
Labels: Domain

#228 Save credits to database
  src/main/java/dk/sdu/swe/presentation/controllers/modals/credits/CreditListModal.java
Labels: Domain

#234 Separate presentation and domain
  src/main/java/dk/sdu/swe/domain/controllers/ExportController.java
  src/main/java/dk/sdu/swe/domain/controllers/contracts/IExportController.java
  src/main/java/dk/sdu/swe/presentation/controllers/DataExportViewController.java
Labels: Domain
